version: "0.1"
services:
  
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default-pro.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/srv
    depends_on:
      - php
      - nodejs
  nodejs:
      image: node:alpine
      environment: 
        NODE_ENV: production
      working_dir: /home/app
      restart: always
      volumes:
        - ./frontend:/home/app
      depends_on:
        - php
      command: sh -c "npm install && npm run build"
  php:
      image: php:apache
      volumes:
        - ./backend:/var/www/html/api



        